NANOSECONDS = 1
MICROSECONDS = 1000 * NANOSECONDS
MILLISECONDS = 1000 * MICROSECONDS
SECONDS = 1000 * MILLISECONDS

MINE_RATE = 10 * SECONDS

STARTING_BALANCE = 50

MINING_REWARD = 50
MINING_REWARD_INPUT = { 'address': '*--official-mining-reward--asus_rig*' }