# Generated by Django 5.2.7 on 2025-10-01 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('height', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('last_hash', models.CharField(db_index=True, max_length=128)),
                ('timestamp', models.BigIntegerField(db_index=True)),
                ('difficulty', models.IntegerField()),
                ('nonce', models.BigIntegerField()),
            ],
            options={
                'db_table': 'block',
                'ordering': ['height'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tx_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_reward', models.BooleanField(default=False)),
                ('timestamp', models.BigIntegerField(db_index=True)),
                ('from_address', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.block')),
            ],
            options={
                'db_table': 'transaction',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MetadataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(db_index=True, max_length=128)),
                ('metadata', models.JSONField()),
                ('stored_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_store', to='core.transaction')),
            ],
            options={
                'db_table': 'metadata_store',
            },
        ),
        migrations.CreateModel(
            name='TransactionInputActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=128)),
                ('amount', models.BigIntegerField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='core.transaction')),
            ],
            options={
                'db_table': 'transaction_input_activity',
                'unique_together': {('transaction', 'address')},
            },
        ),
        migrations.CreateModel(
            name='TransactionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=128)),
                ('amount', models.BigIntegerField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='core.transaction')),
            ],
            options={
                'db_table': 'transaction_output',
                'unique_together': {('transaction', 'address')},
            },
        ),
    ]
